language: ruby
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.10.6
addons:
    code_climate:
        repo_token: 04e5a8142d8a9c41028d505f4fe22d5fd371ea48c49372e7397903beddef0d6f
