module MazeExamples
  def cells_grid
    [
      [
        MazeMagic::Edge.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::Edge.instance
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::Passage.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::Passage.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::Passage.instance,
        MazeMagic::VerticalWall.instance,
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::VerticalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::VerticalWall.instance,
      ]
    ]
  end

  def cells_grid_1by1
    [
      [
        MazeMagic::Edge.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::Edge.instance
      ],
      [
        MazeMagic::VerticalWall.instance,
        MazeMagic::HorizontalWall.instance,
        MazeMagic::VerticalWall.instance
      ]
    ]
  end
end
